# Generated by Django 5.2.5 on 2025-08-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
